version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: db_fiap
    restart: always
    environment:
      POSTGRES_USER: fiapuser
      POSTGRES_PASSWORD: fiappass
      POSTGRES_DB: fiapdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fiap

  app:
    image: dttpaula/grupo16-1techchallenge:1.0
    container_name: api_fiap
    depends_on:
      - postgres
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/fiapdb
      SPRING_DATASOURCE_USERNAME: fiapuser
      SPRING_DATASOURCE_PASSWORD: fiappass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
    networks:
      - fiap

networks:
  fiap:
    driver: bridge

volumes:
  postgres_data: