spring:
  application:
    name: gestrest

datasource:
   url: jdbc:postgresql://postgres:5432/gestrest
   username: admin
   password: admin
      
mvc:
    problemdetails:
      enabled: true  # ativa respostas RFC 7807

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# OpenAPI/Swagger (Springdoc)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

gestrest:
  jwt:
    # chave de exemplo - troque por uma string aleatória longa em produção
    secret: "gestrest-super-secret-key-32-chars-minimo-123"
    expiration-minutes: 60
